### ISSUE TITLE
The file tree sometimes steals focus

### ISSUE THREAD

**Issue by iammerrick** [philc/textmatevim#9]
When this plugin is installed, and creating a new file with a project open you can no type in the new file unless textmate is restarted. ProjectPlus is also installed.

**Comment by philc** [comment]
It may be because the project drawer is focused. Try hitting tab a few times to focus the cursor back into the text area.

I've seen this and I'm not sure what causes it.

**Comment by iammerrick** [comment]
Interesting I uninstalled because of this, I will reinstall and see if tabbing out works out.

**Comment by philc** [comment]
Hey Merrick, any luck?

**Comment by iammerrick** [comment]
Tabbing out does solve the problem. I wonder in TextMate vim would be causing this. Thank you for the awesome plugin!

**Comment by philc** [comment]
Textmatevim might be causing it. If so, I should be able to find a workaround.

**Comment by iammerrick** [comment]
I can only assume it is textmatevim because I  only have this problem when using textmatevim. However it could be a collision with ProjectPlus & TextMateVim

**Comment by ddeyoung** [comment]
I don't have ProjectPlus and I've also been experiencing this since I installed textmatevim. I'm going to try tabbing next time it happens, but I've also found that I can close or close/open the project drawer to get back into the open file. I've also experienced this issue while moving between files and not just creating a new file.
